<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CodePage>65001</CodePage>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yanzi.Shared\Yanzi.Shared.csproj" />
  </ItemGroup>

</Project>
