<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.5.5</Version>
    <AssemblyName>Yanzi.UI.Wpf</AssemblyName>
    <RootNamespace>Yanzi.UI.Wpf</RootNamespace>
  </PropertyGroup>
</Project>
