name = "openquickhost-sync"
main = "src/index.js"
compatibility_date = "2026-04-23"

[vars]
ALLOW_DEV_VERIFICATION_CODES = "true"

[[d1_databases]]
binding = "DB"
database_name = "openquickhost-sync-db"
database_id = "512f99ac-4f5f-4e30-affb-58fc4da94bfa"

[[r2_buckets]]
binding = "PACKAGES"
bucket_name = "openquickhost-sync-assets"
