using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace OpenQuickHost.Sync;

public static class SyncCryptoService
{
    private const int Pbkdf2Iterations = 50000;
    private const int KeySizeBits = 256;
    private const int KeySizeBytes = KeySizeBits / 8;
    private const int NonceSizeBytes = 12; // 96 bits for GCM
    private const int TagSizeBytes = 16;   // 128 bits for GCM

    /// <summary>
    /// Derives the 256-bit MasterKey and LoginHash from the master password and salt (email).
    /// </summary>
    public static (byte[] MasterKey, string LoginHash) DeriveKeys(string password, string email)
    {
        if (string.IsNullOrEmpty(password)) throw new ArgumentException("密码不能为空", nameof(password));
        if (string.IsNullOrEmpty(email)) throw new ArgumentException("邮箱不能为空", nameof(email));

        var salt = Encoding.UTF8.GetBytes(email.Trim().ToLowerInvariant());
        var pwdBytes = Encoding.UTF8.GetBytes(password);

        // Derive MasterKey using PBKDF2 with SHA-256
        using var pbkdf2 = new Rfc2898DeriveBytes(pwdBytes, salt, Pbkdf2Iterations, HashAlgorithmName.SHA256);
        var masterKey = pbkdf2.GetBytes(KeySizeBytes);

        // Derive LoginHash from MasterKey using HMAC-SHA256
        using var hmac = new HMACSHA256(masterKey);
        var loginHashBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes("login-verification"));
        var loginHash = Convert.ToHexString(loginHashBytes).ToLowerInvariant();

        return (masterKey, loginHash);
    }

    /// <summary>
    /// Encrypts plain text using AES-GCM with the derived MasterKey.
    /// Returns a base64 encoded string format: "base64(nonce):base64(tag):base64(ciphertext)"
    /// </summary>
    public static string Encrypt(string plainText, byte[] masterKey)
    {
        if (string.IsNullOrEmpty(plainText)) return string.Empty;
        if (masterKey == null || masterKey.Length != KeySizeBytes) 
            throw new ArgumentException("MasterKey 必须为 256 位", nameof(masterKey));

        var plainBytes = Encoding.UTF8.GetBytes(plainText);
        var nonce = new byte[NonceSizeBytes];
        var tag = new byte[TagSizeBytes];
        var cipherBytes = new byte[plainBytes.Length];

        // Generate a cryptographically secure random nonce
        RandomNumberGenerator.Fill(nonce);

        using (var aesGcm = new AesGcm(masterKey, TagSizeBytes))
        {
            aesGcm.Encrypt(nonce, plainBytes, cipherBytes, tag);
        }

        var nonceBase64 = Convert.ToBase64String(nonce);
        var tagBase64 = Convert.ToBase64String(tag);
        var cipherBase64 = Convert.ToBase64String(cipherBytes);

        return $"{nonceBase64}:{tagBase64}:{cipherBase64}";
    }

    /// <summary>
    /// Decrypts cipher text generated by Encrypt using the derived MasterKey.
    /// Expects format: "base64(nonce):base64(tag):base64(ciphertext)"
    /// </summary>
    public static string Decrypt(string encryptedPayload, byte[] masterKey)
    {
        if (string.IsNullOrEmpty(encryptedPayload)) return string.Empty;
        if (masterKey == null || masterKey.Length != KeySizeBytes) 
            throw new ArgumentException("MasterKey 必须为 256 位", nameof(masterKey));

        var parts = encryptedPayload.Split(':');
        if (parts.Length != 3) 
            throw new FormatException("加密密文格式非法，无法解密。");

        try
        {
            var nonce = Convert.FromBase64String(parts[0]);
            var tag = Convert.FromBase64String(parts[1]);
            var cipherBytes = Convert.FromBase64String(parts[2]);
            var plainBytes = new byte[cipherBytes.Length];

            using (var aesGcm = new AesGcm(masterKey, TagSizeBytes))
            {
                aesGcm.Decrypt(nonce, cipherBytes, tag, plainBytes);
            }

            return Encoding.UTF8.GetString(plainBytes);
        }
        catch (CryptographicException ex)
        {
            throw new CryptographicException("解密失败：密文可能被篡改，或解密密钥不匹配。", ex);
        }
        catch (Exception ex)
        {
            throw new FormatException("解密时遇到异常，数据损坏。", ex);
        }
    }

    /// <summary>
    /// Performs a cryptographic self-test to ensure the E2EE encryption/decryption works properly.
    /// </summary>
    public static void SelfTest()
    {
        var password = "TestPassword123!";
        var email = "test@example.com";
        var originalText = "Hello, World! E2EE Secure Payload.";

        var (masterKey, loginHash) = DeriveKeys(password, email);
        var encrypted = Encrypt(originalText, masterKey);
        var decrypted = Decrypt(encrypted, masterKey);

        if (originalText != decrypted)
        {
            throw new CryptographicException("E2EE 自检失败：加密解密内容不一致。");
        }

        if (string.IsNullOrEmpty(loginHash) || loginHash.Length != 64)
        {
            throw new CryptographicException("E2EE 自检失败：LoginHash 长度非法。");
        }
    }
}

